version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.25
    ports:
      - "1192:1192"
    depends_on:
      - php
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../wordpress:/usr/share/nginx/html:cached

  php:
    container_name: php
    build: ./
    depends_on:
      - database
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ../wordpress:/usr/share/nginx/html:cached

  database:
    container_name: database
    image: mysql:8.3
    platform: linux/x86_64
    environment:
      - MYSQL_DATABASE=my_app
      - MYSQL_USER=my_app
      - MYSQL_PASSWORD=secret
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - TZ=Japan
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    ports:
      - "33061:3306"
    volumes:
      - database-vol:/var/lib/mysql:cached

volumes:
  database-vol:
